/** Static demo data when no server JSON is present (e.g. /demo/client-profile-dashboard). */
export const DEMO_PAYLOAD = {
    client: {
        id: 193,
        name: 'Jane Doe',
        position: 'Senior Event Coordinator',
        company: 'Global Tech Solutions',
        email: 'jane.doe@gts.com',
        phone: '+1 (555) 123-4567',
        address: 'San Francisco, CA',
        genderLabel: 'Female',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&q=80',
        coverUrl: null,
        coverPosition: 'center center',
    },
    stats: {
        totalBooths: 15,
        totalBookings: 23,
        paidBooths: 12,
        totalRevenue: 14500,
        confirmed: 0,
        reserved: 0,
        cancelled: 2,
        boothsRingPct: 75,
        paidRingPct: 75,
    },
    primaryTags: ['CES', 'Dreamforce'],
    activity: [
        { variant: 'log', title: 'Log: Call about booth requirements', date: 'Jan 12th' },
        { variant: 'success', title: 'CES Booking Confirmed', date: 'Jan 15th' },
        { variant: 'note', title: 'Note added regarding custom booth design', date: 'Jan 18th' },
    ],
    upcomingEvents: [
        {
            name: "Dreamforce '24 Booth",
            date: 'Sep 10th - 11th',
            location: 'SF Moscone',
            statusLabel: 'Confirmed',
            statusTone: 'green',
        },
        {
            name: "CES '25 Booth",
            date: 'Jan 8th - 11th',
            location: 'Las Vegas',
            statusLabel: 'Reservation',
            statusTone: 'yellow',
        },
        {
            name: "InnovateX '25 Gala",
            date: 'Mar 1st',
            location: 'San Jose',
            statusLabel: 'Planning',
            statusTone: 'gray',
        },
    ],
    routes: {
        dashboard: '#',
        clientsIndex: '#',
        clientEdit: '#',
        clientBack: '#',
        booksIndex: '#',
        boothsIndex: '#',
        floorPlansIndex: '#',
        affiliatesIndex: '#',
        hrDashboard: '#',
        financeDashboard: '#',
        usersIndex: '#',
        settingsIndex: '#',
    },
    user: {
        initial: 'V',
        username: 'vutha_admin',
        roleLabel: 'Administrator',
    },
};
